version: "3.9"

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    networks:
      - springboot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app_container
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres_data: { }