spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://postgre:RnwL6dYs3cf8mjaVfwWKQSSYyPvhadjI@dpg-cs8hs05umphs7387psv0-a/postgre_979k
    username: postgre
    password: RnwL6dYs3cf8mjaVfwWKQSSYyPvhadjI
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: false
    validate-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /doc